---
title: "library(tidyverse)"
output: html_notebook
---

```{r include=FALSE}
library(tidyverse)
library(hexbin)
```

two type questions:
variation with variables/covariation between variables

```{r}
# bar chart - dist of categorical var
diamonds %>% count(cut) # count 
diamonds %>% ggplot(aes(x = cut)) + geom_bar()
```

```{r}
# histogram - dist of continous var
diamonds %>% ggplot(aes(x = carat)) + geom_histogram(binwidth = .5)
# calculate 
diamonds %>% count(cut_width(carat,0.5))
```

```{r}
# smaller binwidth
smaller <- diamonds %>% filter(carat < 3)
ggplot(smaller,aes(x = carat)) + geom_histogram(binwidth = 0.1)

# geom_freqploy use lines
smaller %>% ggplot(aes(x = carat,color = cut)) + geom_freqpoly(binwidth = 0.1)
```

```{r}
# outliers
ggplot(data = diamonds) + geom_histogram(mapping = aes(x = y),binwidth = .5) + coord_cartesian(ylim = c(0,50))

# unusual
unusual <- diamonds %>% filter(y<3|y>20) %>% arrange(y)
unusual
```

```{r}
# replace unusual values with missing values
diamonds2 <- diamonds %>% mutate(y = ifelse(y<3|y>20,NA,y))
diamonds2 %>% ggplot(aes(x = x,y = y)) + geom_point(na.rm = TRUE)
```

```{r}
# covariation
# density
ggplot(data = diamonds,mapping = aes(x = price,y = ..density..)) + geom_freqpoly(mapping = aes(color = cut),binwidth = 500)

#boxplot
diamonds %>% ggplot(aes(x = cut,y = price)) + geom_boxplot()
mpg %>% ggplot() + geom_boxplot(mapping = aes(x = reorder(class,hwy,FUN = median),y = hwy))+coord_flip()
```

```{r}
# covariation between two categorical
diamonds %>% ggplot() + geom_count(mapping = aes(x = cut,y = color))
diamonds %>% count(cut,color)
```

```{r}
# covariation between two categorical
diamonds %>% ggplot() + geom_count(mapping = aes(x = cut,y = color))
diamonds %>% count(cut,color) %>% ggplot(mapping = aes(x = color,y = cut)) + geom_tile(mapping = aes(fill = n))
```

```{r}
# covariation between two countinous
diamonds %>% ggplot(aes(x = carat,y = price)) + geom_point(alpha = 1/100) # alpha - avoid overlapping
smaller %>% ggplot() + geom_bin2d(aes(x = carat,y = price))
smaller %>% ggplot() + geom_hex(aes(x = carat,y = price))
smaller %>% ggplot(aes(x = carat,y = price)) + geom_boxplot(aes(group = cut_width(carat,0.1))) # cut continous into bins
smaller %>% ggplot(aes(x = carat,y = price)) + geom_boxplot(aes(group = cut_number(carat,20))) # same number of points in each bin
```

```{r}
# models
library(modelr)
mod <- lm(log(price) ~ log(carat),data = diamonds)
diamonds2 <- diamonds %>% add_residuals(mod) %>% mutate(resid = exp(resid))
diamonds2 %>% ggplot() + geom_point(aes(x = carat,y = resid))
diamonds2 %>% ggplot() + geom_boxplot(aes(x = cut,y = resid))
```
